import React from 'react';
import { MemeData } from '../types';
import { Copy, Check, Laugh } from 'lucide-react';

interface MemeCardProps {
  data: MemeData | null;
  loading: boolean;
  id?: string;
}

export const MemeCard: React.FC<MemeCardProps> = ({ data, loading, id }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    if (data?.text) {
      navigator.clipboard.writeText(data.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) {
    return (
      <div className="relative w-full max-w-md bg-white flex flex-col items-center justify-center p-8 text-slate-800 shadow-2xl rounded-xl overflow-hidden border-2 border-orange-200">
        <div className="animate-pulse flex flex-col items-center gap-6 w-full">
          <div className="h-12 w-12 bg-orange-200 rounded-full"></div>
          <div className="h-4 bg-slate-300 rounded w-3/4"></div>
          <div className="h-4 bg-slate-300 rounded w-1/2"></div>
          <div className="h-4 bg-slate-300 rounded w-2/3 mt-8"></div>
          <div className="h-8 bg-slate-200 rounded-lg w-32 mt-4"></div>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="relative w-full max-w-md bg-gradient-to-br from-orange-50 to-teal-50 flex flex-col items-center justify-center p-12 text-slate-400 border-4 border-dashed border-orange-300 rounded-xl">
        <Laugh size={56} className="mb-6 text-orange-300" />
        <p className="font-medium text-center text-lg mb-2">Select your category</p>
        <p className="text-sm text-center">Generate your first Bengali meme!</p>
      </div>
    );
  }

  return (
    <div className="relative group w-full max-w-md">
      <div 
        id={id} 
        className="relative w-full bg-gradient-to-br from-white to-orange-50 flex flex-col items-center justify-between p-8 text-slate-900 shadow-2xl rounded-xl select-none border-4 border-teal-600"
        style={{
          fontFamily: "'Noto Sans Bengali', 'SolaimanLipi', 'Arial', sans-serif"
        }}
      >
        {/* Top Logo Section */}
        <div className="flex flex-col items-center gap-1 mb-4">
          <img
            src="/saatmishaali-logo.png"
            alt="Saatmishaali Logo"
            className="opacity-90"
            style={{
              width: '48px',
              height: '40px',
            }}
          />
          <span className="text-xs font-black tracking-[0.15em] uppercase text-teal-700">
            Saatmishaali
          </span>
        </div>

        {/* Meme Text Container */}
        <div className="flex-1 flex items-center justify-center py-6 px-4 w-full">
          <div className="bg-gradient-to-r from-orange-100 to-yellow-50 p-6 rounded-lg border-2 border-orange-200 w-full">
            <p className="text-2xl md:text-3xl font-bold text-center leading-relaxed text-slate-800">
              {data.text}
            </p>
          </div>
        </div>

        {/* Meme Template Indicator */}
        <div className="mt-6 px-4 py-2 bg-orange-500 rounded-full">
          <span className="text-sm font-semibold text-teal-900">
            {data.category}  {"Memes"}
          </span>
        </div>

        {/* Bottom Watermark */}
        <div className="mt-6 flex flex-col items-center gap-1">
          <span className="text-[10px] font-medium text-slate-500 tracking-wider">
            Generated by Saatmishaali AI
          </span>
          <div className="h-px w-16 bg-gradient-to-r from-transparent via-orange-400 to-transparent"></div>
        </div>
      </div>

      {/* Action Overlay */}
      <button 
        onClick={handleCopy}
        className="absolute top-4 right-4 p-2 bg-white/90 hover:bg-white text-teal-700 rounded-full shadow-lg transition-all opacity-0 group-hover:opacity-100 backdrop-blur-sm border border-teal-200"
        title="Copy Meme Text"
      >
        {copied ? <Check size={18} className="text-green-600" /> : <Copy size={18} />}
      </button>
    </div>
  );
};